[build]
  base = "."  # Use current directory
  publish = "build"  # Assuming build folder is in root
  command = "npm install --no-cache && npm run build"  # Command to install dependencies and build the React app

[dev]
  command = "npm start"  # Command to run your React app locally

[build.environment]
  # Set environment variables needed for the build
  REACT_APP_API_URL = "https://flask-api-74jq.onrender.com/api/chat"  # Change this to your Flask API URL
  NODE_ENV = "production"  # Ensure production mode is set
  NODE_VERSION = "16"  # Optional: specify Node.js version, update as needed

# Redirects configuration (if necessary)
[[redirects]]
  from = "/api/*"  # Redirect any API requests
  to = "https://flask-api-74jq.onrender.com/api/:splat"  # Forward requests to your Flask API
  status = 200
  force = true

# Custom headers (if needed)
[[headers]]
  for = "/*"
  [headers.values]
    # Example to enable CORS
    Access-Control-Allow-Origin = "*"
